name: Build Raspberry Pi Image

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: read  # Allow read access to the repository contents
        
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Set up QEMU for ARM
              uses: docker/setup-qemu-action@v2
      
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
      
            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y qemu-user-static coreutils zip unzip rsync dosfstools debootstrap zerofree parted pigz
      
            - name: Run pi-gen build
              run: |
                sudo ./build-docker.sh
      
            - name: Upload built image
              uses: actions/upload-artifact@v2
              with:
                name: fleet_os_image
                path: deploy/*.img