name: Base Custom Raspberry Pi OS

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-22.04  # Avoid latest to ensure stability

    permissions:
      contents: read  # Read access to repo

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up QEMU for ARM
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static coreutils zip unzip rsync dosfstools debootstrap zerofree parted pigz

      - name: Run pi-gen Build
        run: |
          sudo ./build-docker.sh

      - name: Manually clone upload-artifact action
        run: |
          git clone https://github.com/actions/upload-artifact.git ./.github/actions/upload-artifact
        
      - name: Upload Built Image (manual fallback)
        uses: ./.github/actions/upload-artifact
        with:
            name: fleet_os_base
            path: deploy/*.img
        
