name: Base Custom Raspberry Pi OS

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-22.04  # Avoid latest to ensure stability

    permissions:
      contents: read  # Read access to repo

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up QEMU for ARM
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static coreutils zip unzip rsync dosfstools debootstrap zerofree parted pigz

      - name: Run pi-gen Build
        run: |
          sudo ./build-docker.sh

      - name: Try Upload with Official Action
        id: try_upload
        continue-on-error: true
        uses: actions/upload-artifact@v3.1.2

        with:
          name: fleet_os_base
          path: deploy/*.img
        
      - name: Check if Upload Failed
        if: steps.try_upload.outcome == 'failure'
        run: |
          echo "Fallback to manual upload"
    
      - name: Clone Upload Artifact Manually (Fallback)
        if: steps.try_upload.outcome == 'failure'
        run: |
          git clone https://github.com/actions/upload-artifact.git ./.github/actions/upload-artifact
    
      - name: Manual Upload (Fallback)
        if: steps.try_upload.outcome == 'failure'
        uses: ./.github/actions/upload-artifact
        with:
          name: fleet_os_base
          path: deploy/*.img
        
        
